server_url: "https://erddap.gcoos.org/erddap"
dataset_id: "wmo_42881_2024"
start_date: "2024-04-01T00:00:00Z"
end_date: "2024-04-05T00:00:00Z"
depth_range:
  - 60
  - 240
height_per_plot: 1.0
color_pallete:
  - "pink"
  - "skyblue"
  - "green"
  - "yellow"
  - "orange"
  - "red"
arrow_head: false
output_filename: "plot_output_2d.png"
instrument: 1