server_url: "https://erddap.gcoos.org/erddap"
dataset_id: "wmo_42874"
start_date: "2024-05-01T00:00:00Z"
end_date: "2024-05-09T00:00:00Z"
depth_range:
  - 0
  - 200
height_per_plot: 1.5
color_pallete:
  - "pink"
  - "skyblue"
  - "green"
  - "yellow"
  - "orange"
  - "red"
arrow_head: false
output_filename: "plot_output.png"
instrument: 1